name: chain_reaction
description: "Chain Reaction is a popular strategic board game played by two players, where the objective is to eliminate all opponents by triggering chain reactions that take over the board."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  window_size: ^0.1.0
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.13.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  image_path: "assets/icon/app_icon.png"